# Csv configuration file.

# Location of the OCaml compiler and tools.
#----------------------------------------------------------------------
# The defaults should be OK.
OCAMLC     = ocamlc
OCAMLOPT   = ocamlopt
OCAMLDEP   = ocamldep
OCAMLDOC   = ocamldoc
OCAMLFIND  = ocamlfind
OCAMLTAGS  = ocamltags

# The location of OCaml's library files.
OCAMLLIBDIR := $(shell $(OCAMLC) -where)

# Installation
#----------------------------------------------------------------------
# The "install" program.
INSTALL := install
#INSTALL := /usr/ucb/install

# This is where we will install the documentation.
DOCDIR = /usr/share/doc/$(PACKAGE)-$(VERSION)


# Utilities
#----------------------------------------------------------------------
LN	= /bin/ln -sf
SED	= sed
